image: haskell:8.0.1

before_script:
    - RC=1; while [ $RC -eq 1 ]; do apt-get update -y; apt-get install -y -qq git-core dh-autoreconf pkg-config libgtk-3-dev; RC=$?; done

howl_test:
  cache:
    untracked: true
    paths:
      - .stack-work
      - ___restore
  script:
    - mkdir -p `pwd`/___restore
    - ln -s `pwd`/___restore /root/.stack
    - stack --no-terminal build howl-backend