image: haskell:8.0.1

before_script:
    - RC=1; while [ $RC -eq 1 ]; do apt-get update -y; apt-get install -y -qq git-core dh-autoreconf pkg-config libgtk-3-dev; RC=$?; done
    - stack setup;

howl_test:
  cache:
    untracked: true
    paths:
      - .stack-work
      - ___restore
  script:
    - mkdir -p `pwd`/___restore
    - ln -s `pwd`/___restore /root/.stack
<<<<<<< HEAD
    - stack --no-terminal build howl-backend
=======
    - stack --no-terminal build howl-backend
>>>>>>> 1e012220d93ffb08036f90e53f1eda37ab5e49a2
