image: haskell:8.0.1

before_script:
    - stack setup;

howl_test:
  cache:
    untracked: true
    paths:
      - .stack-work
  script:
    - stack --no-terminal test howl-backend:howl-backend-test --coverage
