FROM fpco/stack-run:latest

RUN mkdir -p /bin
RUN mkdir -p .ebextensions
WORKDIR /bin

RUN apt-get update
RUN apt-get install -y libpq-dev

COPY howl-backend /bin/howl-backend
COPY app.cfg      /bin/app.cfg

EXPOSE 3000

CMD ["/bin/howl-backend"]
