FROM fpco/stack-run:latest

RUN mkdir -p /bin
WORKDIR /bin

RUN apt-get update
RUN apt-get install -y libpq-dev

COPY howl-backend /bin/howl-backend
COPY app.cfg      /bin/app.cfg
COPY swagger-generated.json      /static-files/swagger-generated.json

EXPOSE 3000

CMD ["/bin/howl-backend"]
