FROM fpco/stack-run:latest

RUN mkdir -p /bin
WORKDIR /bin

RUN apt-get update
RUN apt-get install -y libpq-dev
RUN ln -sf /proc/1/fd/1 /var/log/webserver.log


COPY howl-backend /bin/howl-backend
COPY swagger-generated.json      /static-files/swagger-generated.json

EXPOSE 3000

CMD ["/bin/howl-backend"]
