flags: {}
packages:
- '.'
- location:
    git: git@github.com:collegevine/firebase.git
    commit: master
  extra-dep: true
- location:
    git: git@github.com:ralphmorton/nano-http.git
    commit: master
  extra-dep: true
extra-deps:
  - aeson-casing-0.1.0.5
  - esqueleto-2.5.3
  - json-stream-0.4.1.5
resolver: lts-10.3
